

name: Java CI with Gradle

	on: # events
  push: # event
    branches: [ master ]
  pull_request: # event
    branches: [ master ]

jobs: # combination of actions
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
			run: chmod +x gradlew
    
    - name: Build with Gradle
			run: ./gradlew build
